# Canvas Dark
[colors]
background   = "#141821"
foreground = "#d2d2cd"
cursor_bg    = "#a786f0"
cursor_fg    = "#141821"
cursor_border= "#a896f0"
selection_bg = "#242a34"
selection_fg = "#d2d2cd"

ansi   = ["#141821","#e06c75","#6f8f74","#d2b06b","#8ea4c3","#a896f0","#9a8fc0","#d2d2cd"]
brights= ["#5b606a","#f28b93","#90b890","#e0c48a","#b0c0d8","#c2b7ff","#bfb3e6","#ffffff"]

[color_schemes."Canvas Light"]
[color_schemes."Canvas Light".colors]
foreground = "#2b2d33"
background = "#f8f7f2"
cursor_bg = "#8076b8"
cursor_border = "#8076b8"
cursor_fg = "#f8f7f2"
selection_bg = "#efede6"
selection_fg = "#2b2d33"
# scrollbar_thumb = "#d8d4cb"
# split = "#d8d4cb"
# ansi = ["#efede6","#a64646","#4f6a8f","#9a7a3e","#4f6684","#6f60b0","#8076b8","#2b2d33"]
# brights = ["#b8bbc2","#bf5959","#5d7aa6","#b08b4b","#637a9f","#7f73c8","#8f86c6","#3b3e45"]
